"""add_field_in_phone.

Revision ID: 2df29793459b
Revises: 5adf29f22542
Create Date: 2022-10-19 10:37:36.842905
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2df29793459b"
down_revision = "5adf29f22542"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
